<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
   <ApplicationIcon>Res\BlueFlame.ico</ApplicationIcon>
   <MyType>WindowsForms</MyType>
   <OutputType>WinExe</OutputType>
   <StartupObject>Sub Main</StartupObject>
   <UseWindowsForms>true</UseWindowsForms>
   <ImportedNamespaces>System.Data=False,System.Drawing=False,System.ServiceProcess=False,System.Windows.Forms=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,SysPurge=True</ImportedNamespaces>  
</PropertyGroup>

   <PropertyGroup>
      <Platforms>x64;x86</Platforms>
      <TargetFrameworks>net48;net8.0-windows;net10.0-windows</TargetFrameworks>
      <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
      <BaseOutputPath>..\bin\</BaseOutputPath>
      <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
   </PropertyGroup>

   <PropertyGroup Condition="'$(TargetFramework)'=='net48' AND '$(Configuration)|$(Platform)'=='Debug|x86'">
      <OutputPath>..\bin\Debug\net4.8 x86\</OutputPath>
      <IntermediateOutputPath>obj\Debug\net4.8 x86\</IntermediateOutputPath>
   </PropertyGroup>
   <PropertyGroup Condition="'$(TargetFramework)'=='net48' AND '$(Configuration)|$(Platform)'=='Debug|x64'">
      <OutputPath>..\bin\Debug\net4.8\x64\</OutputPath>
      <IntermediateOutputPath>obj\Debug\net4.8 x64\</IntermediateOutputPath>
   </PropertyGroup>
   <PropertyGroup Condition="'$(TargetFramework)'=='net48' AND '$(Configuration)|$(Platform)'=='Release|x86'">
      <OutputPath>..\bin\Release\net4.8 x86\</OutputPath>
      <IntermediateOutputPath>obj\Release\net4.8 x86\</IntermediateOutputPath>
   </PropertyGroup>
   <PropertyGroup Condition="'$(TargetFramework)'=='net48' AND '$(Configuration)|$(Platform)'=='Release|x64'">
      <OutputPath>..\bin\Release\net4.8 x64\</OutputPath>
      <IntermediateOutputPath>obj\Release\net4.8 x64\</IntermediateOutputPath>
   </PropertyGroup>

   <PropertyGroup Condition="'$(TargetFramework)'=='net8.0-windows' AND '$(Configuration)|$(Platform)'=='Debug|x86'">
      <OutputPath>..\bin\Debug\net8.0 x86\</OutputPath>
      <IntermediateOutputPath>obj\Debug\net8.0 x86\</IntermediateOutputPath>
   </PropertyGroup>
   <PropertyGroup Condition="'$(TargetFramework)'=='net8.0-windows' AND '$(Configuration)|$(Platform)'=='Debug|x64'">
      <OutputPath>..\bin\Debug\net8.0 x64\</OutputPath>
      <IntermediateOutputPath>obj\Debug\net8.0 x86\</IntermediateOutputPath>
   </PropertyGroup>
   <PropertyGroup Condition="'$(TargetFramework)'=='net8.0-windows' AND '$(Configuration)|$(Platform)'=='Release|x86'">
      <OutputPath>..\bin\Release\net8.0 x86\</OutputPath>
      <IntermediateOutputPath>obj\Release\net8.0 x86\</IntermediateOutputPath>
   </PropertyGroup>
   <PropertyGroup Condition="'$(TargetFramework)'=='net8.0-windows' AND '$(Configuration)|$(Platform)'=='Release|x64'">
      <OutputPath>..\bin\Release\net8.0 x64\</OutputPath>
      <IntermediateOutputPath>obj\Release\net8.0 x86\</IntermediateOutputPath>
   </PropertyGroup>

   <PropertyGroup Condition="'$(TargetFramework)'=='net10.0-windows' AND '$(Configuration)|$(Platform)'=='Debug|x86'">
      <OutputPath>..\bin\Debug\net10.0 x86\</OutputPath>
      <IntermediateOutputPath>obj\Debug\net10.0 x86\</IntermediateOutputPath>
   </PropertyGroup>
   <PropertyGroup Condition="'$(TargetFramework)'=='net10.0-windows' AND '$(Configuration)|$(Platform)'=='Debug|x64'">
      <OutputPath>..\bin\Debug\net10.0 x64\</OutputPath>
      <IntermediateOutputPath>obj\Debug\net10.0 x86\</IntermediateOutputPath>
   </PropertyGroup>
   <PropertyGroup Condition="'$(TargetFramework)'=='net10.0-windows' AND '$(Configuration)|$(Platform)'=='Release|x86'">
      <OutputPath>..\bin\Release\net10.0 x86\</OutputPath>
      <IntermediateOutputPath>obj\Release\net10.0 x86\</IntermediateOutputPath>
   </PropertyGroup>
   <PropertyGroup Condition="'$(TargetFramework)'=='net10.0-windows' AND '$(Configuration)|$(Platform)'=='Release|x64'">
      <OutputPath>..\bin\Release\net10.0 x64\</OutputPath>
      <IntermediateOutputPath>obj\Release\net10.0 x86\</IntermediateOutputPath>
   </PropertyGroup>

   <ItemGroup>
   <Import Include="System.Data" />
   <Import Include="System.Drawing" />
   <Import Include="System.ServiceProcess" />
   <Import Include="System.Windows.Forms" />
</ItemGroup>

<ItemGroup>
   <Content Include="Res\BlueFlame.ico" />
</ItemGroup>

<ItemGroup>
   <Compile Update="Forms\frmReg.vb" />
   <Compile Update="Forms\frmApps.vb">
     <SubType>Form</SubType>
   </Compile>
   <Compile Update="Forms\frmMSApps.vb">
     <SubType>Form</SubType>
   </Compile>
   <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
   </Compile>
   <Compile Update="My Project\Resources.Designer.vb">
     <DesignTime>True</DesignTime>
     <AutoGen>True</AutoGen>
     <DependentUpon>Resources.resx</DependentUpon>
   </Compile>
</ItemGroup>

<ItemGroup>
   <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
   </None>
</ItemGroup>

<ItemGroup>
  <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.9" />
</ItemGroup>

<ItemGroup>
  <EmbeddedResource Update="My Project\Resources.resx">
    <CustomToolNamespace>My.Resources</CustomToolNamespace>
    <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
    <LastGenOutput>Resources.Designer.vb</LastGenOutput>
  </EmbeddedResource>
</ItemGroup>

<ItemGroup>
  <Folder Include="API\" />
</ItemGroup>

</Project>